
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("24bdb4c1-e53d-43f6-9b7c-679fd084b4e7")>
#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class EVSEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new EVSEntities object using the connection string found in the 'EVSEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=EVSEntities", "EVSEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new EVSEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "EVSEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new EVSEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "EVSEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Users() As ObjectSet(Of User)
        Get
            If (_Users Is Nothing) Then
                _Users = MyBase.CreateObjectSet(Of User)("Users")
            End If
            Return _Users
        End Get
    End Property

    Private _Users As ObjectSet(Of User)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToUsers(ByVal user As User)
        MyBase.AddObject("Users", user)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="EVSModel", Name:="User")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class User
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new User object.
    ''' </summary>
    ''' <param name="id">Initial value of the ID property.</param>
    ''' <param name="userName">Initial value of the UserName property.</param>
    ''' <param name="password">Initial value of the Password property.</param>
    ''' <param name="userType">Initial value of the UserType property.</param>
    Public Shared Function CreateUser(id As Global.System.Int64, userName As Global.System.String, password As Global.System.String, userType As Global.System.String) As User
        Dim user as User = New User
        user.ID = id
        user.UserName = userName
        user.Password = password
        user.UserType = userType
        Return user
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ID() As Global.System.Int64
        Get
            Return _ID
        End Get
        Set
            If (_ID <> Value) Then
                OnIDChanging(value)
                ReportPropertyChanging("ID")
                _ID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ID")
                OnIDChanged()
            End If
        End Set
    End Property

    Private _ID As Global.System.Int64
    Private Partial Sub OnIDChanging(value As Global.System.Int64)
    End Sub

    Private Partial Sub OnIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property UserName() As Global.System.String
        Get
            Return _UserName
        End Get
        Set
            OnUserNameChanging(value)
            ReportPropertyChanging("UserName")
            _UserName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("UserName")
            OnUserNameChanged()
        End Set
    End Property

    Private _UserName As Global.System.String
    Private Partial Sub OnUserNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnUserNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Password() As Global.System.String
        Get
            Return _Password
        End Get
        Set
            OnPasswordChanging(value)
            ReportPropertyChanging("Password")
            _Password = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Password")
            OnPasswordChanged()
        End Set
    End Property

    Private _Password As Global.System.String
    Private Partial Sub OnPasswordChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnPasswordChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property UserType() As Global.System.String
        Get
            Return _UserType
        End Get
        Set
            OnUserTypeChanging(value)
            ReportPropertyChanging("UserType")
            _UserType = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("UserType")
            OnUserTypeChanged()
        End Set
    End Property

    Private _UserType As Global.System.String
    Private Partial Sub OnUserTypeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnUserTypeChanged()
    End Sub

    #End Region

End Class

#End Region


